language: go

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6

go:
  - "1.10.x"

before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90

script:
  - make test-coverage codecov

stages:
  - name: push to dockerhub
    if: tag IS present

jobs:
  include:
    - stage: push to dockerhub
      script:
        - PKG_OS=linux make build
        - DOCKER_PUSH_LATEST=true make docker-push
