language: go

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6

go:
  - "1.10.x"

before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90

stages:
  - name: release to github
    if: tag IS present

jobs:
  include:
    - stage: "Test"
      name: "Unit Tests"
      script: make test-coverage codecov
    - script: make test-sdk
      name: "SDK Integration Tests Linux"
    - script: make test-sdk
      name: "SDK Integration Tests OSX"
      os: osx
      osx_image: xcode9.4	
      before_install: echo "skipping before_install for macOS"
    - script:
        - make protogen
        - make no-changes-in-commit
        # check that proto files are buildable by python
        - sudo apt-get --no-install-recommends -y install python3-pip
        - sudo pip3 install -U pip setuptools wheel
        - pip3 install --user grpcio-tools
        - export PY_OUT_DIR=py
        - mkdir -p "$PY_OUT_DIR" && python3 -m grpc_tools.protoc -Isdk --python_out=$PY_OUT_DIR --grpc_python_out=$PY_OUT_DIR sdk/*.proto
      name: "Protobuf code generation"
    - stage: build sd packages
      name: linux packages
      script: PKG_OS="linux" make packages-sdk
    - stage: build sd packages
      name: osx packages
      os: osx
      osx_image: xcode9.4	
      before_install: echo "skipping before_install for macOS"
      script: PKG_OS="darwin" make packages-sdk
    - stage: release to github
      name: linux packages
      script: PKG_OS="linux" make packages-sdk
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*.tar.gz
        skip_cleanup: true
        on:
          all_branches: true
    - stage: release to github
      name: osx packages
      os: osx
      osx_image: xcode9.4	
      before_install: echo "skipping before_install for macOS"
      script: PKG_OS="darwin" make packages-sdk
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*.tar.gz
        skip_cleanup: true
        on:
          all_branches: true

cache:
  directories:
    - $HOME/protoc
    - $HOME/.cache/pip/wheels
