language: go

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6

os:
  - linux
  - osx

osx_image: xcode9.4

go:
  - "1.10.x"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90;
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90;
    fi

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: make test-coverage codecov
    - stage: release to github
      name: linux packages
      script:
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            export PKG_OS="darwin";
          else;
            export PKG_OS="linux";
          fi
        - make packages-sdk

cache:
  directories:
    - $HOME/protoc
    - $HOME/.cache/pip/wheels
